// All Category
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST"
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS"
export const FETCH_ALLCATEGORY_SUCCESS="FETCH_ALLCATEGORY_SUCCESS"
export const FETCH_ALLCATEGORY_REQUEST='FETCH_ALLCATEGORY_REQUEST'
export const FETCH_ALLCATEGORY_FAIL='FETCH_ALLCATEGORY_REQUEST'
export const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL"
export const FETCH_REMOVECATEGORY_SUCCESS="FETCH_REMOVECATEGORY_SUCCESS"
export const FETCH_CLICKCATEGORY_SUCCESS="FETCH_CLICKCATEGORY_SUCCESS"
//ALL SUBCATEGORY
export const FETCH_SUBCATEGORY_REQUEST = "FETCH_SUBCATEGORY_REQUEST"
export const FETCH_SUBCATEGORY_SUCCESS = "FETCH_SUBCATEGORY_SUCCESS"
export const FETCH_SUBCATEGORY_FAIL = "FETCH_SUBCATEGORY_FAIL"

// Comapny
export const FETCH_COMPANY_REQUEST=" FETCH_COMPANY_REQUEST"
export const FETCH_COMPANY_SUCCESS=" FETCH_COMPANY_SUCCESS"
export const FETCH_COMPANY_FAIL=" FETCH_COMPANY_FAIL"